// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phprhrwiuhalxdifdzgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBocHJocndpdWhhbHhkaWZkemduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjQzMjQsImV4cCI6MjA3MjUwMDMyNH0.8_F5kXbA49-sVEh96t8gfHvppnPczqB71qLAHvIkaSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});